### PR TITLE
Add uba logo and specify directors + jury

### PR DESCRIPTION
**Pull request by jdemonasterio**
- Adds university logo 
- adds director, codirector, juries
- minor pdf metadata

### CODE REVIEW

**Comment by petobens** [comment]
Please add the `250x-UBA.png` file to repo (otherwise this won't compile).

**Comment by jdemonasterio** [comment]
Lol so right

**Review by cs4rraute — APPROVED** [review]
Excelente!

**Comment by jdemonasterio** [comment]
@petobens logo was added 👍 if you wanna check title page design 😅

**Comment by petobens** [comment]
Should everything fit on a single page? (currently it takes 2 pages). Is there some reference template?

**Comment by jdemonasterio** [comment]
@petobens I haven't found a reference template or UBA styleguide for that matter. If you think you have a prettier style to fit in 1 page go ahead I'll take the chagnes:). 

It's a more personal matter than anything else so do as you wish 👍

**Comment by petobens** [comment]
See #9

**Pull request merged**
